format = """
$username\
$hostname \
$directory \
$git_branch \
$git_status \
$git_metrics\
$line_break\
$character"""

[username]
style_user = 'white'
style_root = 'white'
format = '[$user]($style)'
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '@[$hostname](white)'

[directory]
style = "#77bdfb"
format = "[$path]($style)"
truncation_length = 3
truncate_to_repo = false
truncation_symbol = "../"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
style = "dimmed #faa356"
format = '([$conflicted$staged$modified$renamed$deleted]($style))'
staged = '[$count](dimmed #a2d2fb)'
modified = '[$count](dimmed black)'
deleted = '[-$count](dimmed #fa7970)'

[git_metrics]
disabled = false
added_style = "dimmed #7ce38b"
deleted_style = "dimmed #fa7970"
format = '([+$added]($added_style) )([-$deleted]($deleted_style) )'

[character]
success_symbol = '[▸](green)'
error_symbol = '[▸](red)'